import os

def translate_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        text = f.read()
    
    for vi, en in replacements.items():
        text = text.replace(vi, en)
        
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(text)

admin_replacements = {
    "Bảng điều khiển quản trị hệ thống": "System Administration Dashboard",
    "Tên đăng nhập": "Username",
    "Mật khẩu": "Password",
    "Đăng Nhập": "Sign In",
    "Tổng Quan": "Dashboard",
    "Người Dùng": "Users",
    "Giao Dịch": "Transactions",
    "Từ Điển Hiệu Đề": "Mark Dictionary",
    "Lịch Sử Scan": "Scan History",
    "Cài Đặt": "Settings",
    "Đăng Xuất": "Sign Out",
    "Doanh Thu 7 Ngày": "7-Day Revenue",
    "Lượt Scan 7 Ngày": "7-Day Scans",
    "Danh Sách Người Dùng": "User List",
    "Tìm kiếm...": "Search...",
    "Lượt Scan": "Scans",
    "Chi Tiêu": "Spent",
    "Quản Lý Các Gói Nâng Cấp": "Upgrade Packages Management",
    "Gói Cơ Bản": "Basic Package",
    "Số tiền (VNĐ)": "Amount (VND)",
    "Lượt phân tích": "Analysis Credits",
    "Gói Phổ Biến": "Popular Package",
    "Gói Chuyên Nghiệp": "Professional Package",
    "Cập Nhật Các Gói": "Update Packages",
    "Quản Lý Giao Dịch": "Transaction Management",
    "Tất cả": "All",
    "Chờ xử lý": "Pending",
    "Hoàn thành": "Completed",
    "Thất bại": "Failed",
    "Số Tiền": "Amount",
    "Trạng Thái": "Status",
    "Mã GD": "Txn Code",
    "Tìm hiệu đề...": "Search mark...",
    "Thêm Mới": "Add New",
    "Chữ Hán": "Chinese Characters",
    "4 Chữ": "4 Chars",
    "Tên Việt": "Vietnamese Name",
    "Triều Đại": "Dynasty",
    "Hoàng Đế": "Emperor",
    "Lịch Sử Phân Tích AI": "AI Analysis History",
    "Ảnh": "Image",
    "Kết Quả": "Result",
    "Thời Gian": "Time",
    "Cấu Hình Tín Dụng (Credits)": "Credit Configuration",
    "Tỷ giá Credit": "Credit Exchange Rate",
    "Số tiền VNĐ cần trả cho 1 Credit (dùng cho tính toán gói cước)": "VND amount per 1 Credit (used for package calculation)",
    "Lưu": "Save",
    "Credits miễn phí mặc định": "Default Free Credits",
    "Số lượt phân tích tặng khi đăng ký tài khoản mới": "Analysis credits gifted upon new account registration",
    "Thông Tin Hệ Thống": "System Information",
    "Phiên bản": "Version",
    "Tổng hiệu đề": "Total Marks",
    "Đang tải...": "Loading...",
    "Cập Nhật Credits": "Update Credits",
    "Thao tác": "Action",
    "Cộng thêm": "Add",
    "Trừ bớt": "Subtract",
    "Đặt giá trị": "Set value",
    "Số lượng Credits": "Amount of Credits",
    "Hủy": "Cancel",
    "Xác Nhận": "Confirm",
    "Reset Mật Khẩu": "Reset Password",
    "Mật khẩu mới": "New password",
    "Nhập mật khẩu mới...": "Enter new password...",
    "Thêm Hiệu Đề Mới": "Add New Mark",
    "Chữ Hán (6 chữ)": "Chinese Chars (6 chars)",
    "Chữ Hán (4 chữ)": "Chinese Chars (4 chars)",
    "Chữ Hán 6 (biến thể)": "Chinese Chars 6 (variant)",
    "Biến thể (cách bởi dấu ;)": "Variants (separated by ;)",
    "Phiên âm": "Transcription",
    "Năm bắt đầu": "Start Year",
    "Năm kết thúc": "End Year",
    "Niên hiệu": "Reign Title",
    "Hiệu đề EN": "Mark EN",
    "Ghi chú": "Notes",
    "Mô tả": "Description",
    "Thư pháp": "Calligraphy",
    "Nghệ thuật": "Artistic Features",
    "Đăng nhập thất bại": "Login failed",
    "Lỗi kết nối server": "Server connection error",
    "Quản Lý Người Dùng": "User Management",
    "Chưa có dữ liệu": "No data available",
    "Đã khóa": "Locked",
    "Hoạt động": "Active",
    "Mở khóa": "Unlock",
    "Khóa": "Lock",
    "Chưa có người dùng": "No users available",
    "Cập nhật credits thành công!": "Credits updated successfully!",
    "Lỗi kết nối": "Connection error",
    "Xác nhận khóa tài khoản này?": "Confirm locking this account?",
    "Đã khóa tài khoản": "Account locked",
    "Đã mở khóa tài khoản": "Account unlocked",
    "Vui lòng nhập mật khẩu": "Please enter password",
    "Đã reset mật khẩu": "Password reset successfully",
    "Thành công": "Success",
    "Chưa có giao dịch": "No transactions available",
    "Đã cập nhật cấu hình các gói thành công!": "Package configuration updated successfully!",
    "Lỗi kết nối khi lưu các gói": "Connection error while saving packages",
    "Sửa": "Edit",
    "Xóa": "Delete",
    "Chưa có hiệu đề": "No marks available",
    "Sửa Hiệu Đề": "Edit Mark",
    "Xác nhận xóa hiệu đề này? Hành động không thể hoàn tác!": "Confirm deleting this mark? This action cannot be undone!",
    "Đã xóa hiệu đề": "Mark deleted successfully",
    "Có kết quả": "Has result",
    "Không khớp": "No match",
    "Chưa có lịch sử scan": "No scan history available",
    "Đã lưu cài đặt!": "Settings saved successfully!",
    "-- Chọn --": "-- Select --",
    "Minh Triều": "Ming Dynasty",
    "Thanh Triều": "Qing Dynasty",
    "Nhà Nguyễn (Việt Nam)": "Nguyen Dynasty (Vietnam)",
    "Khác": "Other"
}

if __name__ == '__main__':
    translate_file('admin.html', admin_replacements)
    print("admin.html translated.")
