import re

def run():
    with open('index.html', 'r', encoding='utf-8') as f:
        text = f.read()

    replacements = {
        "Trang chủ": "Home",
        "Quay lại trang chủ": "Back to Home",
        "Bối cảnh lịch sử": "Historical Context",
        "Thư pháp &amp; Bút pháp": "Calligraphy &amp; Brushwork",
        "Đặc điểm nghệ thuật": "Artistic Features",
        "Hệ thống giám định<br>gốm sứ cổ <span>thông minh</span>": "Smart<br>Antique Ceramic <span>Authentication System</span>",
        "Ứng dụng <strong>trí tuệ nhân tạo</strong> để nhận diện và phân tích hiệu đề cổ vật gốm sứ với độ chính xác cao.": "Apply <strong>artificial intelligence</strong> to recognize and analyze antique ceramic marks with high precision.",
        "Trí tuệ nhân tạo đa đại lý": "Multi-agent AI",
        "Phân tích chính xác nguồn gốc và niên đại cổ vật": "Accurately analyze the origin and period of antiques",
        "Bảo tồn di sản văn hóa": "Cultural Heritage Conservation",
        "Lưu trữ và bảo vệ kiến thức truyền thống": "Preserve and protect traditional knowledge",
        "Giám định nhanh chóng": "Fast Authentication",
        "Kết quả chi tiết chỉ trong vài giây": "Detailed results in seconds",
        "Gia nhập hệ thống": "Join the System",
        "Tạo tài khoản mới để bắt đầu": "Create a new account to get started",
        "Đăng nhập để tiếp tục sử dụng hệ thống": "Sign in to continue using the system",
        "Họ và tên đầy đủ...": "Full name...",
        "Tối thiểu 8 ký tự": "Minimum 8 characters",
        "Nhập lại mật khẩu mới": "Re-enter new password",
        "Hoặc kết nối qua": "Or connect with",
        "Đăng nhập bằng Google": "Sign in with Google",
        "Đăng ký bằng Google": "Sign up with Google",
        "Chưa có tài khoản?": "Don't have an account?",
        "Đã có tài khoản?": "Already have an account?",
        "Đăng ký ngay": "Sign up now",
        "Tôi đồng ý với": "I agree to the",
        "Chính sách bảo mật": "Privacy Policy",
        "bao gồm việc sử dụng AI.": "including the use of AI.",
        "Tạo tài khoản →": "Create Account →",
        "Thông tin tài khoản": "Account Information",
        "Lưu thông tin": "Save Information",
        "Đổi mật khẩu": "Change Password",
        "Cập nhật mật khẩu": "Update Password",
        "Đăng xuất": "Sign Out",
        "Quay lại trang chủ": "Back to Home",
        "Giải pháp nhận dạng<br>hiệu đề <span>cổ truyền</span>": "Traditional Mark<br>Recognition <span>Solution</span>",
        "Hệ thống tối tân hỗ trợ quy trình giám định, nhận dạng và phân tích hiệu đề trên nền tảng học bằng thị giác máy tính và trí tuệ nhân tạo.": "State-of-the-art system supporting the authentication, recognition, and analysis of marks based on computer vision and AI.",
        "Lõi Nhận Dạng (AI)": "Recognition Core (AI)",
        "So Khớp Đặc Trưng": "Feature Matching",
        "Nhận dạng Quang học (OCR)": "Optical Character Recognition (OCR)",
        "Hệ thống ứng dụng sức mạnh của mô hình PaddleOCR kết hợp cùng các kỹ thuật xử lý ảnh (Computer Vision) để trích xuất ký tự Hán Nôm từ hình ảnh hiệu đề một cách tự động và ổn định.": "The system applies the power of PaddleOCR combined with Computer Vision techniques to automatically and stably extract Sino-Vietnamese characters from mark images.",
        "So khớp Đặc trưng (ORB)": "Feature Matching (ORB)",
        "Bên cạnh việc đọc chữ, hệ thống triển khai thuật toán ORB (Oriented FAST and Rotated BRIEF) nhằm trích xuất và đối chiếu các điểm đặc trưng hình học, giúp đối soát chéo với cơ sở dữ liệu.": "In addition to reading text, the system deploys the ORB algorithm to extract and match geometric feature points, helping cross-reference with the database.",
        "Cơ sở dữ liệu tập trung": "Centralized Database",
        "Xây dựng kiến trúc lưu trữ có cấu trúc (MySQL) quản lý thông tin các mẫu hiệu đề thuộc các đại triều (Thanh, Minh, Nguyễn), hỗ trợ trích xuất thông tin niên đại và giải nghĩa nhanh chóng.": "Building a structured storage architecture (MySQL) managing information of mark samples belonging to major dynasties (Qing, Ming, Nguyen), supporting rapid extraction of period and interpretation.",
        "Mục tiêu phát triển": "Development Goal",
        "MarkSense AI là một giải pháp phần mềm được thiết kế để hỗ trợ công tác số hóa di sản. Thay vì tra cứu thủ công qua sách vở, hệ thống cung cấp một công cụ đối chiếu kỹ thuật số trực quan, giúp người dùng dễ dàng tiếp cận và tìm hiểu thông tin lịch sử của gốm sứ cổ truyền.": "MarkSense AI is a software solution designed to support heritage digitization. Instead of manual lookup through books, the system provides an intuitive digital matching tool, helping users easily access and understand the historical information of traditional ceramics.",
        "Liên hệ <span>với chúng tôi</span>": "Contact <span>Us</span>",
        "Bạn có câu hỏi hoặc cần hỗ trợ? Đội ngũ chuyên gia của MarkSense AI luôn sẵn sàng.": "Do you have a question or need support? The MarkSense AI expert team is always ready.",
        "Thông tin": "Information",
        "Gửi tin nhắn": "Send Message",
        "Nhập tên của bạn...": "Enter your name...",
        "Bạn cần hỗ trợ điều gì?": "What do you need help with?",
        "Gửi Thông Tin": "Send Information",
        "Hướng dẫn <span>sử dụng</span>": "User <span>Guide</span>",
        "Bắt đầu quá trình nhận dạng và giám định hiệu đề gốm sứ với 3 bước cơ bản trên hệ thống.": "Start the ceramic mark recognition and authentication process with 3 basic steps on the system.",
        "Đăng ký &amp; Xác thực": "Registration &amp; Authentication",
        "Nhấp vào \"Sign In\" ở góc trên cùng bên phải. Tạo tài khoản mới hoặc sử dụng hệ thống đăng nhập một chạm (Google/SSO) để cấp quyền truy cập. Việc định danh là bắt buộc nhằm mục đích lưu trữ lịch sử phân tích cá nhân.": "Click 'Sign In' in the top right corner. Create a new account or use the single sign-on (Google/SSO) system to grant access. Identification is required for storing personal analysis history.",
        "Tải lên &amp; Phân tích": "Upload &amp; Analyze",
        "Tại giao diện trung tâm, tải lên hình ảnh chụp hiệu đề hoặc sử dụng thao tác kéo thả. Nhấp \"Bắt đầu phân tích\" để kích hoạt lõi AI thị giác máy tính xử lý ảnh.": "At the central interface, upload an image of the mark or use drag and drop. Click 'Start Analysis' to activate the computer vision AI core to process the image.",
        "Truy xuất &amp; Lưu trữ": "Retrieve &amp; Store",
        "Hệ thống sẽ trả về kết quả nhận dạng Hán Nôm, phiên âm, triều đại và mẫu tham chiếu từ kho lưu trữ. Báo cáo được tự động lưu trong mục \"History\" để tra cứu sau này.": "The system will return the Sino-Vietnamese recognition result, transcription, dynasty, and reference sample from the archive. The report is automatically saved in the 'History' section for later lookup.",
        "Cam kết": "Commitment",
        "Chính sách <span>bảo mật</span>": "Privacy <span>Policy</span>",
        "An toàn dữ liệu cá nhân của khách hàng và nhà nghiên cứu là ưu tiên hàng đầu tại MarkSense AI.": "The personal data safety of customers and researchers is a top priority at MarkSense AI.",
        "Thu thập tối thiểu": "Minimal Collection",
        "Chúng tôi chỉ thu thập dữ liệu định danh ở mức tối thiểu (email) nhằm duy trì phiên đăng nhập hợp lệ. Các hình ảnh tải lên được tiếp nhận và xử lý cục bộ trên hệ thống server.": "We only collect minimal identity data (email) to maintain a valid login session. Uploaded images are received and processed locally on the server system.",
        "Quyền riêng tư hình ảnh": "Image Privacy",
        "Hình ảnh được tải lên phục vụ trực tiếp cho thuật toán phân tích. Dữ liệu này sẽ được ẩn danh hoàn toàn (anonymized) nếu được sử dụng như một phần của tập huấn luyện (training set) để cải thiện độ chính xác OCR trong tương lai.": "Uploaded images serve directly for the analysis algorithm. This data will be fully anonymized if used as part of a training set to improve future OCR accuracy.",
        "Cơ chế bảo vệ": "Protection Mechanism",
        "Tất cả phiên truyền tải dữ liệu đều được mã hóa theo chuẩn SSL/TLS. Cơ sở dữ liệu và thư mục hình ảnh của người dùng được giới hạn quyền truy cập bằng kiến trúc bảo mật đa tầng.": "All data transmission sessions are encrypted according to SSL/TLS standards. The user's database and image folder are restricted from access by a multi-tier security architecture.",
        "Quy định": "Regulations",
        "Điều khoản <span>dịch vụ</span>": "Terms of <span>Service</span>",
        "Sử dụng hệ thống giải pháp MarkSense AI đồng nghĩa với việc bạn chấp thuận các quy định pháp lý sau.": "Using the MarkSense AI solution system means you accept the following legal regulations.",
        "Miễn trừ trách nhiệm": "Disclaimer",
        "Các báo cáo và kết quả phân tích do AI trả về mang tính tham chiếu và bổ trợ cho công tác giám định chuyên môn. MarkSense AI không chịu trách nhiệm đối với bất kỳ quyết định mua bán, giao dịch hay thẩm định giá trị nào dựa trên hệ thống.": "Reports and analysis results returned by AI are for reference and support for professional authentication. MarkSense AI is not responsible for any buying, selling, trading, or valuation decisions based on the system.",
        "Bản quyền hình ảnh": "Image Copyright",
        "Người dùng cam kết sở hữu hợp pháp hình ảnh tải lên hệ thống. Bất kỳ khiếu nại bản quyền nào phát sinh từ các mẫu cổ vật số hóa do người dùng tải lên sẽ thuộc trách nhiệm của người đó.": "Users commit to legally owning the images uploaded to the system. Any copyright claims arising from digitized antique samples uploaded by users will be their responsibility.",
        "Tài sản trí tuệ": "Intellectual Property",
        "Cấu trúc hệ thống, trọng số mô hình AI, thuật toán xử lý ảnh (Computer Vision) và dữ liệu tham chiếu là tài sản trí tuệ độc quyền của đội ngũ HieuDe Team.": "The system structure, AI model weights, Computer Vision algorithms, and reference data are the exclusive intellectual property of the HieuDe Team.",
        "Giải đáp": "FAQ",
        "Câu hỏi <span>thường gặp</span>": "Frequently Asked <span>Questions</span>",
        "Các vấn đề thường phát sinh trong quá trình sử dụng hệ thống nhận dạng AI.": "Common issues arising during the use of the AI recognition system.",
        "Chi phí sử dụng MarkSense AI là bao nhiêu?": "How much does MarkSense AI cost?",
        "Hệ thống hiện cung cấp tính năng tra cứu cơ sở dữ liệu và 5 lượt phân tích đầu tiên miễn phí cho tất cả tài khoản. Với nhu cầu lưu trữ và nhận dạng khối lượng lớn, người dùng có thể tham khảo bảng giá dịch vụ cao cấp.": "The system currently provides database lookup and the first 5 analysis turns for free for all accounts. For large volume storage and recognition needs, users can refer to the premium service price list.",
        "Hệ thống có nhận diện được chữ khắc chìm, mất nét không?": "Can the system recognize engraved, faded characters?",
        "Lõi OCR của hệ thống có khả năng khôi phục một phần nét mờ dựa trên ngữ cảnh cấu trúc chữ Hán. Tuy nhiên, hình ảnh cần được chụp rõ ràng, đủ ánh sáng, góc chụp vuông góc để tối đa hóa hiệu suất trùng khớp.": "The OCR core of the system is capable of partially restoring faded strokes based on the structural context of Chinese characters. However, images need to be taken clearly, with sufficient light, and at a perpendicular angle to maximize matching performance.",
        "Tính năng quản lý lịch sử phân tích hoạt động ra sao?": "How does the analysis history management feature work?",
        "Toàn bộ tác vụ nhận dạng được ghi nhận và lưu trong bộ nhớ tạm theo phiên làm việc. Chúng tôi đang hoàn thiện cơ sở dữ liệu vĩnh viễn (cùng chức năng xóa thủ công) ở bản cập nhật tới.": "All recognition tasks are recorded and temporarily saved per session. We are completing the permanent database (along with manual deletion functionality) in the upcoming update.",
        "Giới hạn niên đại nhận diện là gì?": "What is the recognition period limit?",
        "Bộ dữ liệu tập trung mạnh nhất vào các mẫu gốm sứ thuộc đại triều nhà Thanh, nhà Minh và nhà Nguyễn. Các niên đại khác (Tống, Nguyên) đang trong quá trình số hóa và tích hợp dần.": "The dataset strongly focuses on ceramic samples belonging to the Qing, Ming, and Nguyen dynasties. Other periods (Song, Yuan) are in the process of digitization and gradual integration.",
        "Mua Lượt Phân Tích": "Buy Analysis Credits",
        "Khai phá bí mật ẩn sau từng cổ vật với công nghệ AI hàng đầu. Chọn gói": "Uncover the secrets behind each antique with leading AI technology. Choose the",
        "của bạn.": "for your collection.",
        "MIỄN PHÍ": "FREE",
        "PHỔ BIẾN NHẤT": "MOST POPULAR",
        "CHUYÊN NGHIỆP": "PRO",
        "tầm": "collection",
        "TOÁN HÀNG NĂM": "BILLED ANNUALLY",
        "tích": "credits",
        "TỐI ĐA": "ENTERPRISE",
        "giới hạn": "Unlimited",
        "Hệ thống xử lý thanh toán": "Payment Processing System",
        "CHUYỂN KHOẢN NGÂN HÀNG": "BANK TRANSFER",
        "Quét QR nhanh": "Quick QR scan",
        "VÍ ĐIỆN TỬ MOMO": "MOMO E-WALLET",
        "THẺ ATM / INTERNET BANKING": "ATM / INTERNET BANKING",
        "TIẾP TỤC THANH TOÁN": "CONTINUE PAYMENT",
        "KẾT NỐI BẢO MẬT 256-BIT AES": "256-BIT AES SECURE CONNECTION",
        "ĐANG HOẠT ĐỘNG": "ACTIVE",
        "XÁC THỰC BỞI SEPAY": "VERIFIED BY SEPAY",
        "TẢI MÃ QR": "DOWNLOAD QR CODE",
        "GIẢ LẬP NHẬN TIỀN": "SIMULATE RECEIVING MONEY",
        "ĐANG CHỜ THANH TOÁN...": "AWAITING PAYMENT...",
        "SỐ TIỀN THANH TOÁN": "PAYMENT AMOUNT",
        "CHỦ TÀI KHOẢN": "ACCOUNT HOLDER",
        "SỐ TÀI KHOẢN": "ACCOUNT NUMBER",
        "NGÂN HÀNG THỤ HƯỞNG": "BENEFICIARY BANK",
        "NỘI DUNG CHUYỂN KHOẢN": "TRANSFER CONTENT",
        "XÁC NHẬN ĐÃ CHUYỂN KHOẢN": "CONFIRM TRANSFER",
        "QUAY LẠI CHỌN PHƯƠNG THỨC": "BACK TO CHOOSE METHOD",
        "Bạn đã hết lượt phân tích miễn phí.": "You have run out of free analysis credits.",
        "Hãy nâng cấp để tiếp tục khám phá kho tàng cổ vật và mở khóa các tính năng chuyên sâu của MarkSense AI.": "Please upgrade to continue exploring the treasure trove of antiques and unlock advanced features of MarkSense AI.",
        "THÊM LƯỢT": "ADD CREDITS",
        "Hệ thống nhận dạng và phân tích hiệu đề": "Mark Recognition and Analysis System",
        "tạo và thị giác máy": "and computer vision.",
        "Chức năng": "Features",
        "Hỗ trợ": "Support",
        "Liên hệ": "Contact",
        "Phường Tân An, Ninh Kiều": "Tan An Ward, Ninh Kieu",
        "Chụp ảnh": "Take Photo",
        "Phân tích ảnh này": "Analyze this image",
        "Đang tải ảnh lên...": "Uploading image...",
        "Phân Tích & <span class=\"rm-blue\">Nhận Dạng Hiệu Đề</span>": "Analyze & <span class=\"rm-blue\">Recognize Mark</span>",
        "Báo Cáo Giám Định Chuyên Sâu": "In-Depth Authentication Report",
        "Tên phiên âm": "Transcription Name",
        "Chữ Hán": "Chinese Character",
        "Triều đại": "Dynasty",
        "Niên hiệu": "Reign Title",
        "Niên đại": "Period",
        "Hiệu đề (en)": "Mark (en)"
    }

    for vi, en in replacements.items():
        text = text.replace(vi, en)
        
    # Set currentLang to 'en' in JS directly
    text = text.replace("var currentLang = localStorage.getItem('marksense_lang') || 'vi';", "var currentLang = 'en';")
    
    with open('index.html', 'w', encoding='utf-8') as f:
        f.write(text)

if __name__ == '__main__':
    run()
